name: dart_acp
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  json_rpc_2: ^4.0.0
  stream_channel: ^2.1.4
  path: ^1.9.1
  logging: ^1.3.0
  mime: ^1.0.5
  all_lint_rules_community: ^0.0.43

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
